name: Build Workflow
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3', 'head', 'jruby-9.4.5.0']
        gemfile: ['1.14.0', '1.15.0', '1.16.1', '1.17.0', '1.18.4', '1.19.1']
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'head' }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rubocop_${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec spec
