name: Build Workflow
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.2', '3.3', '3.4', '4.0', 'head', 'jruby-10.1.1.0', 'jruby-10.0.6.0']
        gemfile: ['1.20.0', '1.21.0', '1.22.3', '1.23.0', '1.24.1', '1.25.1', '1.26.1', '1.27.0', '1.28.2', '1.29.1', '1.30.1']
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'head' }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rubocop_${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler: 2.5.22
        ruby-version: ${{ matrix.ruby }}
        rubygems: latest
    - run: bundle install --jobs 4
    - run: bundle exec rspec spec
